apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jokes-app
  template:
    metadata:
      labels:
        app: jokes-app
    spec:
      containers:
      - image: victorialloyd/python-webapp:v2
        name: python-jokes-app
        ports:
        - containerPort: 5000